<?php
/**
 * @file
 * Main module file, only hooks are allowed here.
 */

/**
 * Constants section.
 */
define('CUSTOM_STATISTICS_DB_TABLE_NAME', 'custom_statistics_db');

/**
 * Require section.
 */
require_once 'includes/custom_statistics.api.inc';
require_once 'model/custom_statistics.db.inc';

/**
 * Registers node hit.
 */
function custom_statistics_node_view($node, $view_mode) {
  global $user;

  if (!custom_statistics_is_node_type_tracked($node->type)) {
    return NULL;
  }
  if (!custom_statistics_is_user_role_tracked($user->roles)) {
    return NULL;
  }

  // If visiting node page. We don't want to register teaser views.
  if ($view_mode == 'full') {
    custom_statistics_register_hit($node->nid, $user->uid);
  }
}

/**
 * Adds settings menu to admin settings page.
 */
function custom_statistics_menu() {
  $items['admin/config/system/custom_statistics'] = array(
    'title' => 'Custom statistics',
    'description' => 'Control node types and user roles that module will track.',
    'file' => 'includes/pages/custom_statistics.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_statistics_admin_settings'),
    'access arguments' => array('administer custom_statistics settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['node/%/custom_statistics'] = array(
    'title' => 'Custom statistics (theme)',
    'page callback' => 'custom_statistics_render_statistics_table',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Defines custom permission rules for showing statistics tab on the node page.
 */
function custom_statistics_permission() {
  return array(
    'custom statistics view tab' => array(
      'title' => t('View custom statistics'),
      'description' => t('Defines who can see "Custom statistics" tab on the node page.'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function custom_statistics_views_api() {
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'custom_statistics') . '/includes/views',
  );
}
